Task_2_2_1
jokerhasnopersonality/OOP pull request #11
Opened 2023-03-14 15:11 UTC by jokerhasnopersonality

2023-03-31 17:58 UTC, alradish requested changes

2023-03-31 17:58 UTC, alradish commented on Task_2_2_1/src/main/java/io/github/jokerhasnopersonality/Storage.java
> +public class Storage {
У вас в этом классе что-то всё смешалось. 
- `storage` хранит заказы, но определяется через `capacity` хотя они по сути не связанны
- Нет синхронизации на storage, кажется, вроде как будет плохо при работе `placeOrder` и  `getFromStorage`
- Ну и вообще создаётся какой-то лишний слой из-за того, что вы храните пиццы в заказе, хотя логичнее было бы их хранить как раз таки в хранилище. Тогда не пришлось бы накручивать 
- Плюс у вас получается так, что деливери могут увезти больше пицц чем размер багажника

Общий совет хранить пиццы в хранилище и позволить деливерям выполнять заказы частично, в таком случае придется следить когда заказ выполнился
Или можно просто сказать Одина заказ - одна пицца

2023-03-31 17:58 UTC, alradish commented on Task_2_2_1/src/main/java/io/github/jokerhasnopersonality/Pizzeria.java
> +            queue.add(new OrderPair(order, order.getPizzaNumbers()[i]));
нет синхронизации

2023-03-31 17:58 UTC, alradish commented on Task_2_2_1/src/main/java/io/github/jokerhasnopersonality/Pizzeria.java
> +    private final Object lock;
Вся работа с синхронизацией должна быть в хранилище. Все остальные просто пользуются его методами и блокируются на них если нужно

2023-04-09 08:31 UTC, alradish requested changes
А как запустить?
Лабу посмотрел, хорошо, в принципе готов зачесть, но мне бы посмотреть как она работает

2023-04-09 17:18 UTC, jokerhasnopersonality commented
> А как запустить? Лабу посмотрел, хорошо, в принципе готов зачесть, но мне бы посмотреть как она работает

Добавила main для удобства. Просто пиццерию запускает с параметрами из ресурсов.

2023-04-25 08:03 UTC, alradish approved these changes

2023-04-25 08:14 UTC, merged